#!/bin/bash

if [ ! -f /cfg/config.json ]; then
	echo "No config file found, copying example config to /cfg/config.json"
	echo "Ensure /data is mounted for persistence"
	cp /app/example_config.json /cfg/config.json
	sed -i "s|\"DatabaseLocation\": \"/data\"|\"DatabaseLocation\": \"/data\"|" /cfg/config.json
	echo "Config generated from example, you may want to edit it and start again"
	echo "IMPORTANT: Update the Wireguard PrivateKey field with a key generated by 'wg genkey'"
  exit
fi

echo "WAG: start"
exec wag start -c /cfg/config.json
